In [88]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [89]:
happiness_dataset = pd.read_csv('happiness_index_dataset (1).csv')

In [90]:
happiness_dataset.head()

,Campus,Infrastructure,Mentoring Program,Parental Involvement,Environment Free of bullying,Social Footprints,Sports,Discipline,Well versed with the subject,Use of presentations,Degree of difficulty of assignments,Solves doubts willingly,Structuring of the course,Provides support for students going above and beyond,Course recommendation based on relevance,Result
0,6,6,5,1,10,1,10,1,10,4,5,1,7,1,10,Moderate Happy
1,5,8,4,1,10,6,4,10,7,4,4,1,4,6,4,Moderate Happy
2,1,2,5,1,10,9,4,4,6,7,5,1,10,9,10,Moderate Happy
3,8,7,6,1,10,3,8,4,6,6,6,1,6,3,8,Moderate Happy
4,10,3,4,1,10,7,2,5,10,8,4,1,10,7,9,Happy

In [91]:
happiness_dataset.tail()

,Campus,Infrastructure,Mentoring Program,Parental Involvement,Environment Free of bullying,Social Footprints,Sports,Discipline,Well versed with the subject,Use of presentations,Degree of difficulty of assignments,Solves doubts willingly,Structuring of the course,Provides support for students going above and beyond,Course recommendation based on relevance,Result
996,5,6,2,10,1,1,10,5,6,4,2,10,10,1,9,Moderate Happy
997,2,8,10,10,1,2,2,4,7,7,10,10,7,2,2,Moderate Happy
998,2,10,8,10,1,2,4,2,7,6,8,10,10,2,8,Happy
999,6,4,6,10,1,3,9,7,6,6,6,10,10,3,9,Happy
1000,2,9,8,10,1,7,8,9,10,6,8,10,7,7,8,Happy

In [92]:
happiness_dataset.dropna()

,Campus,Infrastructure,Mentoring Program,Parental Involvement,Environment Free of bullying,Social Footprints,Sports,Discipline,Well versed with the subject,Use of presentations,Degree of difficulty of assignments,Solves doubts willingly,Structuring of the course,Provides support for students going above and beyond,Course recommendation based on relevance,Result
0,6,6,5,1,10,1,10,1,10,4,5,1,7,1,10,Moderate Happy
1,5,8,4,1,10,6,4,10,7,4,4,1,4,6,4,Moderate Happy
2,1,2,5,1,10,9,4,4,6,7,5,1,10,9,10,Moderate Happy
3,8,7,6,1,10,3,8,4,6,6,6,1,6,3,8,Moderate Happy
4,10,3,4,1,10,7,2,5,10,8,4,1,10,7,9,Happy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,5,6,2,10,1,1,10,5,6,4,2,10,10,1,9,Moderate Happy
997,2,8,10,10,1,2,2,4,7,7,10,10,7,2,2,Moderate Happy
998,2,10,8,10,1,2,4,2,7,6,8,10,10,2,8,Happy
999,6,4,6,10,1,3,9,7,6,6,6,10,10,3,9,Happy
1000,2,9,8,10,1,7,8,9,10,6,8,10,7,7,8,Happy

In [93]:
happiness_dataset['Result'].value_counts()
happiness_dataset.groupby('Result').mean()

,Campus,Infrastructure,Mentoring Program,Parental Involvement,Environment Free of bullying,Social Footprints,Sports,Discipline,Well versed with the subject,Use of presentations,Degree of difficulty of assignments,Solves doubts willingly,Structuring of the course,Provides support for students going above and beyond,Course recommendation based on relevance
Result,,,,,,,,,,,,,,,
Happy,6.057065,7.076087,6.570652,6.692935,5.964674,6.831522,6.548913,5.972826,7.641304,6.201087,6.554348,6.652174,6.288043,6.861413,6.565217
Moderate Happy,5.340249,5.684647,5.087137,5.145228,5.516598,5.338174,5.089212,5.377593,7.497925,5.873444,5.099585,5.130705,5.425311,5.267635,5.296680
Not Happy,4.973510,4.754967,3.788079,3.675497,4.728477,3.986755,3.986755,4.735099,7.145695,5.529801,3.748344,3.701987,4.721854,4.000000,4.205298

In [94]:
X = happiness_dataset.drop(columns = 'Result', axis=1)
Y = happiness_dataset['Result']

In [95]:
scaler = StandardScaler()
scaler.fit(X)
standardized_data = scaler.transform(X)

In [96]:
X = standardized_data
Y = happiness_dataset['Result']

In [97]:
X

array([[ 0.16226218, -0.02136887, -0.15157059, ...,  0.46719832,
        -1.61312883,  1.52559163],
       [-0.19708393,  0.74256811, -0.49876087, ..., -0.56063799,
         0.11682827, -0.55400513],
       [-1.6344684 , -1.54924281, -0.15157059, ...,  1.49503464,
         1.15480253,  1.52559163],
       ...,
       [-1.27512228,  1.50650508,  0.89000028, ...,  1.49503464,
        -1.26713741,  0.83239271],
       [ 0.16226218, -0.78530584,  0.1956197 , ...,  1.49503464,
        -0.92114599,  1.17899217],
       [-1.27512228,  1.12453659,  0.89000028, ...,  0.46719832,
         0.46281969,  0.83239271]])

In [98]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify=Y, random_state=24)

In [99]:
classifier = svm.SVC(kernel='linear')

In [100]:
#training the support vector Machine Classifier
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [101]:
# # accuracy score on the training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [102]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.88375

In [103]:
# accuracy score on the test data
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [104]:
print('Accuracy score of the test data : ', test_data_accuracy)

Accuracy score of the test data :  0.8756218905472637

In [127]:
list1 = [1,5,7,4,6,9,8,2,4,6,2,1,4,7,8]
input_data = (list1)

In [128]:
# changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

In [129]:
# reshape the array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

In [130]:
# standardize the input data
std_data = scaler.transform(input_data_reshaped)

c:\Users\Shailesh Kankarej\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [131]:
print(std_data)

[[-1.6344684  -0.40333735  0.54280999 -0.51731358  0.15228348  1.15581581
   0.87259625 -1.21411364 -2.06689546  0.04094424 -1.19631556 -1.55732541
  -0.56063799  0.46281969  0.83239271]]

In [132]:
prediction = classifier.predict(std_data)
print(prediction)

['Not Happy']